language: generic

servisces: 
  - docker

afer_success:
  - docker build -t daizaria/user-wishlist-app .

  - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_ID' --password-stdin

  - docker push daizaria/user-wishlist-app

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Daizaria-user-wishlist
  env: Daizariauserwishlist-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: 'multi-container-wishlist-daiz'
  bucket_path: 'docker'
  on:
    branch: main  